{% set name = "openvsp" %}
{% set version = "3.30.0" %}

{% if no_graphics %}
{% set build = 100 %}
{% set label = "no_graphics" %}
{% else %}
{% set build = 0 %}
{% set label = "with_graphics" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenVSP/OpenVSP.git
  git_rev: OpenVSP_{{ version }}

build:
  number: {{ build }}
  skip: true  # [py<=36]
  string: py{{ CONDA_PY }}_{{ label }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - no_graphics  # [no_graphics]

requirements:
  build:
    - python {{ python }}
    - cmake
    - make
    - {{ compiler('cxx') }}  # Cf comment above
    - swig
    - eigen
    - cminpack
    - libxml2
    - fltk
    - glm
    - glew
    - openmp
    - libgomp # [linux64]
    - setuptools
  host:
    - python {{ python }}
    - pip
    - swig
    - eigen
    - cminpack
    - libxml2
    - fltk
    - glm
    - glew
    - openmp
    - libgomp # [linux64]
    - setuptools
  run:
    - python
    - numpy
    - matplotlib >=3.1.0
    - scipy
    - pandas
    - fortranformat
    - eigen
    - cminpack
    - libxml2
    - fltk
    - glm
    - glew
    - openmp
    - libgomp # [linux64]

test:
  commands:
    - test -f $PREFIX/bin/vsp  # [no_graphics == "false"]
    - test -f $PREFIX/bin/vspaero

  imports:
    - openvsp

about:
  home: http://openvsp.org/
  license: Other
  license_file: LICENSE
  summary: 'A parametric aircraft geometry tool.'
  description: |
    OpenVSP is a parametric aircraft geometry tool. OpenVSP allows the user to create a 3D model of an aircraft defined by common engineering parameters. This model can be processed into formats suitable for engineering analysis. The predecessors to OpenVSP have been developed by JR Gloudemans and others for NASA since the early 1990's. In January 2012, OpenVSP was released as an open source project under the NOSA 1.3 license. The first open source version was 2.0.0.
  doc_url: http://openvsp.org/docs.shtml
