{% set name = "openvsp" %}
{% set version = "3.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: OpenVSP_{{ version }}.tar.gz
  url: https://github.com/OpenVSP/OpenVSP/archive/refs/tags/OpenVSP_{{ version }}.tar.gz
  sha256: e8536e6eb22ead4a9a8739b3fe21ca4226fa9866b38024463f8fe0907dff52d7

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}  # Cf comment above
    - swig
    - eigen
    - cminpack
    - libxml2
    - fltk
    - glm
    - glew
  host:
    - swig
    - eigen
    - cminpack
    - libxml2
    - fltk
    - glm
    - glew
  run:
    - numpy
    - matplotlib
    - scipy
    - eigen
    - cminpack
    - libxml2
    - fltk
    - glm
    - glew

test:
  commands:
    - test -f $PREFIX/bin/vsp
    - test -f $PREFIX/bin/vspaero

  imports:
    - openvsp

about:
  home: http://openvsp.org/
  license: Other
  license_file: https://github.com/OpenVSP/OpenVSP/blob/main/LICENSE
  summary: 'A parametric aircraft geometry tool.'
  description: |
    OpenVSP is a parametric aircraft geometry tool. OpenVSP allows the user to create a 3D model of an aircraft defined by common engineering parameters. This model can be processed into formats suitable for engineering analysis. The predecessors to OpenVSP have been developed by JR Gloudemans and others for NASA since the early 1990's. In January 2012, OpenVSP was released as an open source project under the NOSA 1.3 license. The first open source version was 2.0.0.
  doc_url: http://openvsp.org/docs.shtml