{% set name = "adept" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: adept-{{ version }}.tar.gz
  url: http://www.met.reading.ac.uk/clouds/adept/adept-{{ version }}.tar.gz
  sha256: 0cef334e82df4526d3761bdd8319a63e7582c96b2f1cc88391729018b4825c47

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}  # Cf comment above
  host:
    - libblas
    - liblapack
  run:
    - libblas
    - liblapack

test:
  commands:
    - test -f $PREFIX/lib/libadept.a

about:
  home: http://www.met.reading.ac.uk/clouds/adept/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: 'Fast automatic differentiation library in C++'
  description: |
    Adept (Automatic Differentiation using Expression Templates) is a free C++
    software library that enables algorithms to be automatically differentiated,
    very useful for a wide range of applications that involve mathematical
    optimization. It uses an operator overloading approach, so very little code
    modification is required. Moreover, the way that expression templates have been
    used and several other important optimizations mean that reverse-mode
    differentiation is significantly faster than other C++ libraries that provide
    equivalent functionality.
    The fundamental object of most mathematical software is the array, and it is
    therefore natural to want to differentiate array expressions. There are numerous
    mature C++ array libraries that support a wide variety of array operations, but
    because they also use expression templates to optimize array expressions, they
    do not work efficiently with Adept. The solution provided in version 2 of
    Adept is to use a single expression-template framework that incorporates both
    array and automatic-differentiation capabilities at a low level, thus enabling
    efficient differentiation of array expressions. Arrays of up to 7 dimensions are
    supported along with matrix multiplication and basic linear algebra operations.
    Of course, the library also works well with passive arrays (those that do not
    need to be differentiated).
  doc_url: http://www.met.reading.ac.uk/clouds/adept/documentation.html
  dev_url: https://github.com/rjhogan/Adept-2
